CREATE TABLE CUSTOMER (
	CUSTOMER_ID INT NOT NULL PRIMARY KEY,
	CUSTOMER_EMAIL VARCHAR(50) NOT NULL,
	CUSTOMER_PASSWORD VARCHAR(50) NOT NULL,
	CUSTOMER_NAME VARCHAR(50) NOT NULL,
	CUSTOMER_ADDRESS VARCHAR(MAX) NOT NULL,
	CUSTOMER_PHONENO VARCHAR(10) NOT NULL
)

CREATE TABLE CATEGORY (
	CATEGORY_ID INT NOT NULL PRIMARY KEY,
	CATEGORY_NAME VARCHAR(20) NOT NULL
)

CREATE TABLE PRODUCT (
	PRODUCT_ID INT NOT NULL PRIMARY KEY,
	PRODUCT_NAME VARCHAR(50) NOT NULL,
	PRODUCT_DESC VARCHAR(50),
	PRODUCT_IMAGE VARBINARY(MAX),
	PRODUCT_PRICE INT NOT NULL,
	CATEGORY_ID INT FOREIGN KEY REFERENCES CATEGORY(CATEGORY_ID)
)

CREATE TABLE ORDER_TBL (
	ORDER_ID INT NOT NULL PRIMARY KEY,
	ORDER_DATE DATE NOT NULL,
	ORDER_TOTAL INT NOT NULL,
	CUSTOMER_ID INT FOREIGN KEY REFERENCES CUSTOMER(CUSTOMER_ID)
)

CREATE TABLE ORDER_DETAILS (
	ORDER_DETAILS_ID INT NOT NULL PRIMARY KEY,
	PRODUCT_ID INT FOREIGN KEY REFERENCES PRODUCT(PRODUCT_ID),
	PRODUCT_QTY INT NOT NULL,
	PRODUCT_PRICE INT NOT NULL,
	ORDER_ID INT FOREIGN KEY REFERENCES ORDER_TBL(ORDER_ID),
	SUB_TOTAL INT NOT NULL
)